### ISSUE TITLE
"--help" throws error

### ISSUE THREAD

**Issue by Anzo52** [Anzo52/SnaptPip3#3]
`Traceback (most recent call last):
  File "SnaptPip3.py", line 273, in <module>
    main()
  File "SnaptPip3.py", line 233, in main
    option = sys.argv[2]
IndexError: list index out of range`

**Comment by Anzo52** [comment]
https://github.com/Anzo52/SnaptPip3/blob/f66664760cacf01e74eea6e8506e500aa68767fa/SnaptPip3.py#L236
